services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gaaunikh-app:iteration1
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CommerceDatabase: Host=postgres;Port=5432;Database=gaaunikh;Username=gaaunikh;Password=gaaunikh
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gaaunikh
      POSTGRES_USER: gaaunikh
      POSTGRES_PASSWORD: gaaunikh
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    profiles: ["infra"]
    ports:
      - "6379:6379"

volumes:
  pgdata:
